### ISSUE TITLE
User Interface Mock-ups

### ISSUE THREAD

**Issue by jhryniw** [CMPUT301F17T13/cat-is-a-dog#10]
Provide screen mock-ups for each interface interacting with defined use cases (#9).

**Deliverables:**
- [x] At least one design made for each outlined User Interface
- [x] Completed one storyboard
- [x] User Interface mock-ups are posted on the project wiki
- [x] Use cases attached to each design

**Comment by jhryniw** [comment]
@lelandjansen @abidrahman 
List of user interfaces to complete:

- [ ] Habit Summary Interface (three screens: My Habits, Todo, Following) 
- [ ] Habit Details Interface
- [ ] Add Habit Interface
- [ ] Edit Habit Interface
- [ ] Habit History Interface (common screen: My Events, Following Events, All Events)
- [ ] Add Habit Event Interface (complete todo habit)
- [ ] Habit Event Details Interface
- [ ] Edit Habit Event Interface
- [ ] User Friends Interface (following and followers)
- [ ] User Follow Request Interface
- [ ] User Search Interface

**Comment by lelandjansen** [comment]
Done! Nice work @abidrahman!
