### ISSUE TITLE
Project video screen captures

### ISSUE THREAD

**Issue by lelandjansen** [CMPUT301F17T13/cat-is-a-dog#104]
Summary: Take screen captures for each app interaction in the video by **Tuesday December 5 at 20:00**.

I am putting together the project movie. The idea is to superimpose a screen capture of the app being used on top of the video to show how it works. For example, while Kevin creates a habit show a screen capture that follows his narration creating a habit, entering a title and reason, etc. Please create a fluid sequence for each app interaction in the movie and match the narration as closely as you can. The screen captures must be at least 1080 px tall.

The video can be found here (work in progress): https://adobe.ly/2jLlvo9

I need time to incorporate these screen captures into the video. Please have this task completed by December 5 at 20:00.

**Comment by abidrahman** [comment]
List of video snippets:
- Logging in
- Adding a habit (get funding, reason: hire people to do real work, start:today, repeats: T, R)
- Add a habit event (habit: disrupt the industry, habit event: did it)
- Add a habit (work from home)
- Search and follow users (elon musk and bill gates)
- Look at followers' habits on summary page
- Add habit (buy bitcoin)

**Comment by abidrahman** [comment]
Videos 2 to 9:
[2-9.zip](https://github.com/CMPUT301F17T13/cat-is-a-dog/files/1529431/2-9.zip)

**Comment by lelandjansen** [comment]
Not sure if this was deliberate, but "work" is misspelled in #2.

**Comment by lelandjansen** [comment]
Need completed habit event for "Get VC funding".
