### ISSUE TITLE
Make Wiki

### ISSUE THREAD

**Issue by nwlieb** [CMPUT301F17T13/cat-is-a-dog#11]
- [x] Use cases
- [x] Add Mockup / Storyboard images (@abidrahman and @lelandjansen)
- [x] Finalize Mockups / Storyboard page (@nwlieb)
- [x] Glossary, add terminology and competing products (@nwlieb)
- [x] Release planning (@nwlieb)

**Comment by lelandjansen** [comment]
Done!
