### ISSUE TITLE
Reference issue in TODO

### ISSUE THREAD

**Issue by lelandjansen** [CMPUT301F17T13/cat-is-a-dog#16]
Whenever making a `TODO` item in the code, please create a GitHub issue and reference it. For example:
```
TODO(#16): Create issue for this TODO and reference the issue #
```

**Comment by jhryniw** [comment]
Our only TODO so far is #17. Can I close this issue?

**Comment by lelandjansen** [comment]
Don't forget to update the code ;)

**Comment by lelandjansen** [comment]
I count 5 PR comments referencing #16.

**Comment by jhryniw** [comment]
Made the rest reference #18. Will keep this issue open for reminder purposes

**Comment by lelandjansen** [comment]
Project finished.
