### ISSUE TITLE
Project part 3: Peer review

### ISSUE THREAD

**Issue by lelandjansen** [CMPUT301F17T13/cat-is-a-dog#19]
Please leave a comment describing your contributions for part 3. Check the box next to your name when you have left a commend and filled out the peer review form.
- [x] @nwlieb 
- [x] @Megasonic988 
- [x] @jhryniw 
- [x] @lelandjansen
- [x] @abidrahman 

Due October 30.

**Comment by lelandjansen** [comment]
My contributions (work in progress)
* Code review for base

**Comment by jhryniw** [comment]
My contributions (work in progress)

- Developed basic class structure for the entire app
- Translated above into an application base

**Comment by abidrahman** [comment]
My contributions (work in progress)

- Create Unit tests for the following model classes: Habit, HabitEvent, HabitStatus

**Comment by nwlieb** [comment]
My contributions
- Fixed usecase spreadsheet to markdown converter script
- Create Unit tests for the following model classes: CurrentUser, FollowRequest, User

**Comment by Megasonic988** [comment]
My Contributions

- Designed classes and app structure with James and Abid

- Wrote skeletal code for classes, adding on to James' work

- Create model classes in UML diagram

**Comment by linster** [comment]
Learned about this library at KotlinConf, you guys might like to check it out for debugging:

http://facebook.github.io/stetho/
