### ISSUE TITLE
TestFile contributions 

### ISSUE THREAD

**Issue by lelandjansen** [CMPUT301F17T13/cat-is-a-dog#2]
Please make an edit to `TestFile.txt` to meet Project 1's requirements (in a pull request). Related to #1.

- [x] @lelandjansen
- [x] @nwlieb 
- [x] @jhryniw 
- [x] @megasonic988
- [x] @abidrahman

**Comment by lelandjansen** [comment]
Process:
1. Checkout  `master` and pull
2. Make a branch with your edit (and push that branch)
3. Make a pull request with your branch. Delete the branch (locally and remotely) when you're finished,

**Comment by jhryniw** [comment]
Everyone has completed their changes. Good work!

**Comment by lelandjansen** [comment]
Reopening this issue because because `blame` shows that @nwlieb made @megasonic988's edit. 

@Megasonic988: Please resolve.

**Comment by jhryniw** [comment]
Lool, that might have been my bad

**Comment by lelandjansen** [comment]
Looks like we don't care?

**Comment by lelandjansen** [comment]
@nwlieb No need to remove yourself as an assignee when the work is complete. The data can be useful later if you want to filter old issues you addressed.
