### ISSUE TITLE
Project part 3: Addressing Feedback

### ISSUE THREAD

**Issue by lelandjansen** [CMPUT301F17T13/cat-is-a-dog#20]
> Address any TA feedback on the previous project part.

- [x] @nwlieb Fix wiki script 
- [x] @lelandjansen Address general comments/fixups
- [x] @lelandjansen Dependencies

Due October 23.

**Comment by nwlieb** [comment]
Done

**Comment by lelandjansen** [comment]
I'm not done. Reopening...

**Comment by nwlieb** [comment]
Sorry there was only one checkbox so I thought that was all, my bad
