### ISSUE TITLE
Project part 3:  Object-Oriented Analysis and Design

### ISSUE THREAD

**Issue by lelandjansen** [CMPUT301F17T13/cat-is-a-dog#21]
>Document your initial object-oriented analysis and design using a UML class diagram (or diagrams), focusing on the most important anticipated classes, interfaces, and relationships. Include detail on key attributes and methods. Include notes on the use of design patterns among the classes. Add notes if the purpose of a class or interface is likely not clear to an outsider. The diagram(s) may be reverse engineered from the code, but must be edited, arranged, and selective (not a raw dump). The diagram(s) must be neat and tidy, and drawn well using computer tools and embedded as image(s) in your team wiki. The diagram(s) will likely evolve.

Due October 23

**Comment by jhryniw** [comment]
Application base #15 and UML #26

**Comment by jhryniw** [comment]
Was handed in on October 23
