### ISSUE TITLE
Project part 3: Unit Testing

### ISSUE THREAD

**Issue by lelandjansen** [CMPUT301F17T13/cat-is-a-dog#22]
> Write runnable unit tests for your model classes. Code is required, but the implementation of the model classes need not be complete.

Due October 23

**Comment by abidrahman** [comment]
I'm working on the following model classes:

- [ ] Habit
- [ ] HabitEvent
- [ ] HabitStatus

**Comment by jhryniw** [comment]
Was handed in on October 23
