### ISSUE TITLE
Decouple Firebase from App

### ISSUE THREAD

**Issue by jhryniw** [CMPUT301F17T13/cat-is-a-dog#33]
One major issue I foresee is changing from a Firebase architecture to another architecture. Is there any way we can decouple / encapsulate the Firebase functions/subscribers from the actual Activities themselves?

**Comment by jhryniw** [comment]
Had a conversation with Ken about Firebase. He was satisfied that the Firebase features were under the hood for our model classes, but was apprehensive about not being able to easily switch from a Firebase back-end to another back-end. Should talk to Ian about this further.

**Comment by nwlieb** [comment]
done
