### ISSUE TITLE
Project Part 4 Feedback

### ISSUE THREAD

**Issue by jhryniw** [CMPUT301F17T13/cat-is-a-dog#62]
Complete the feedback forms for #49. Please list your contributions to the project below in order to help the others complete their forms.

- [x] @lelandjansen 
- [x] @jhryniw
- [x] @Megasonic988 
- [x] @abidrahman 
- [x] @nwlieb 
 

Pro tip: Search "is:pr author:yourusername " to view the PRs to which you contributed.

**Comment by jhryniw** [comment]
My contributions:

- Login Activity
- Google OAuth authentication
- Firebase authentication
- Set up Firebase database
- Firebase datasources for Habits and Habit Events
- Paired with @abidrahman for the action bar and navigation drawer
- Refactored UML Diagram

**Comment by lelandjansen** [comment]
My contributions:
* Edit habit (and merged with add habit)
* View habit 
* Delete habit
* Java docs
* Paired with @jhryniw to integrate Firebase
* Miscellaneous tests

**Comment by Megasonic988** [comment]
My contributions:
- Habit summary tab view
- My Habits list
- Todo Habits list
- Create Habit
- Reuse statement

**Comment by nwlieb** [comment]
My contributions:

- AddHabitEventActivity and associated tests
- Integrated Espresso Intents for gallery mocking
- Fix Delete Button for EditHabit/ViewHabit
- Integrated google maps

**Comment by abidrahman** [comment]
My contributions:

- Created Navigation Drawer super class.
- Implemented Navigation Drawer in main classes.
- Refactored/Regression tested unit tests.

**Comment by jhryniw** [comment]
Everyone completed the feedback.
