### ISSUE TITLE
Project Part 5: Peer review

### ISSUE THREAD

**Issue by lelandjansen** [CMPUT301F17T13/cat-is-a-dog#88]
Please list your contributions to the project below to help the others complete their forms.

- [x] @lelandjansen 
- [x] @jhryniw
- [x] @Megasonic988 
- [x] @abidrahman 
- [x] @nwlieb 
 

Pro tip: Search "is:pr author:yourusername" to view the PRs to which you contributed.

**Comment by lelandjansen** [comment]
* Created date util functions
* Started work on filtering backed algorithm (not used)
* Filtering UI
* Supporting code as required
* Project video filming, narration, and editing

**Comment by jhryniw** [comment]
- Created Following Habits page
- Created data sources for habit events by comment or by habit
- Created testing platform to interface with mock firebase server
- Habit Summary UI tests
- Updated UML Documentation
- Created Javadocs for utils and model classes
- Completion Metrics for Habits
- Properly closing Firebase Listeners

**Comment by wkevwang** [comment]
* Social Menu
* Following tab
* Followers tab
* Requests tab
* Search Users tab
* UI tests for Social components
* Project video ideas and acting

**Comment by nlieb** [comment]
* Part of Javadocs
* Habit history UI (excluding filter alert)
* Small part of habit history Firebase Integration
* Edit habit event
* Proximity queries for habit history using Geofire

**Comment by abidrahman** [comment]
- Habit History UI Tests
- Habit Event Deletion
- Completion Metrics Graph
- Habit History Nav Drawer
- Video Demo App Screens
